version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/blitz/Dockerfile
    volumes:
      - ./:/myapp
      - /myapp/node_modules
    ports:
      - 3000:3000
    command: sh -c "yarn prisma generate && yarn start"
